#!/bin/bash

# Example:
#   1.0 - 45014ca (build: 65)
V="$(cat mac.json | jq --raw-output .version) - $(git rev-parse --short HEAD) (build: $(git rev-list --all --count))";

go build

pushd ./app
REACT_APP_VERSION=$V npm run build
popd

rm -rf ./resources
cp -r ./app/build ./resources
cp ./app/src/base/logo.png ./resources/logo.png

macpack build
