// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("PostHistories", testPostHistories)
	t.Run("Posts", testPosts)
	t.Run("TeamMembers", testTeamMembers)
	t.Run("Teams", testTeams)
	t.Run("UserCreateCodes", testUserCreateCodes)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesDelete)
	t.Run("Posts", testPostsDelete)
	t.Run("TeamMembers", testTeamMembersDelete)
	t.Run("Teams", testTeamsDelete)
	t.Run("UserCreateCodes", testUserCreateCodesDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesQueryDeleteAll)
	t.Run("Posts", testPostsQueryDeleteAll)
	t.Run("TeamMembers", testTeamMembersQueryDeleteAll)
	t.Run("Teams", testTeamsQueryDeleteAll)
	t.Run("UserCreateCodes", testUserCreateCodesQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesSliceDeleteAll)
	t.Run("Posts", testPostsSliceDeleteAll)
	t.Run("TeamMembers", testTeamMembersSliceDeleteAll)
	t.Run("Teams", testTeamsSliceDeleteAll)
	t.Run("UserCreateCodes", testUserCreateCodesSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesExists)
	t.Run("Posts", testPostsExists)
	t.Run("TeamMembers", testTeamMembersExists)
	t.Run("Teams", testTeamsExists)
	t.Run("UserCreateCodes", testUserCreateCodesExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesFind)
	t.Run("Posts", testPostsFind)
	t.Run("TeamMembers", testTeamMembersFind)
	t.Run("Teams", testTeamsFind)
	t.Run("UserCreateCodes", testUserCreateCodesFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesBind)
	t.Run("Posts", testPostsBind)
	t.Run("TeamMembers", testTeamMembersBind)
	t.Run("Teams", testTeamsBind)
	t.Run("UserCreateCodes", testUserCreateCodesBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesOne)
	t.Run("Posts", testPostsOne)
	t.Run("TeamMembers", testTeamMembersOne)
	t.Run("Teams", testTeamsOne)
	t.Run("UserCreateCodes", testUserCreateCodesOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesAll)
	t.Run("Posts", testPostsAll)
	t.Run("TeamMembers", testTeamMembersAll)
	t.Run("Teams", testTeamsAll)
	t.Run("UserCreateCodes", testUserCreateCodesAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesCount)
	t.Run("Posts", testPostsCount)
	t.Run("TeamMembers", testTeamMembersCount)
	t.Run("Teams", testTeamsCount)
	t.Run("UserCreateCodes", testUserCreateCodesCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesHooks)
	t.Run("Posts", testPostsHooks)
	t.Run("TeamMembers", testTeamMembersHooks)
	t.Run("Teams", testTeamsHooks)
	t.Run("UserCreateCodes", testUserCreateCodesHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesInsert)
	t.Run("PostHistories", testPostHistoriesInsertWhitelist)
	t.Run("Posts", testPostsInsert)
	t.Run("Posts", testPostsInsertWhitelist)
	t.Run("TeamMembers", testTeamMembersInsert)
	t.Run("TeamMembers", testTeamMembersInsertWhitelist)
	t.Run("Teams", testTeamsInsert)
	t.Run("Teams", testTeamsInsertWhitelist)
	t.Run("UserCreateCodes", testUserCreateCodesInsert)
	t.Run("UserCreateCodes", testUserCreateCodesInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("PostToUserUsingCreatedBy", testPostToOneUserUsingCreatedBy)
	t.Run("PostToUserUsingDeletedBy", testPostToOneUserUsingDeletedBy)
	t.Run("PostToTeamUsingOwnedBy", testPostToOneTeamUsingOwnedBy)
	t.Run("PostToUserUsingUpdatedBy", testPostToOneUserUsingUpdatedBy)
	t.Run("TeamMemberToTeamUsingTeam", testTeamMemberToOneTeamUsingTeam)
	t.Run("TeamMemberToUserUsingUser", testTeamMemberToOneUserUsingUser)
	t.Run("UserCreateCodeToUserUsingUser", testUserCreateCodeToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("TeamToOwnedByPosts", testTeamToManyOwnedByPosts)
	t.Run("TeamToTeamMembers", testTeamToManyTeamMembers)
	t.Run("UserToCreatedByPosts", testUserToManyCreatedByPosts)
	t.Run("UserToDeletedByPosts", testUserToManyDeletedByPosts)
	t.Run("UserToUpdatedByPosts", testUserToManyUpdatedByPosts)
	t.Run("UserToTeamMembers", testUserToManyTeamMembers)
	t.Run("UserToUserCreateCodes", testUserToManyUserCreateCodes)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("PostToUserUsingCreatedByPosts", testPostToOneSetOpUserUsingCreatedBy)
	t.Run("PostToUserUsingDeletedByPosts", testPostToOneSetOpUserUsingDeletedBy)
	t.Run("PostToTeamUsingOwnedByPosts", testPostToOneSetOpTeamUsingOwnedBy)
	t.Run("PostToUserUsingUpdatedByPosts", testPostToOneSetOpUserUsingUpdatedBy)
	t.Run("TeamMemberToTeamUsingTeamMembers", testTeamMemberToOneSetOpTeamUsingTeam)
	t.Run("TeamMemberToUserUsingTeamMembers", testTeamMemberToOneSetOpUserUsingUser)
	t.Run("UserCreateCodeToUserUsingUserCreateCodes", testUserCreateCodeToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("PostToUserUsingDeletedByPosts", testPostToOneRemoveOpUserUsingDeletedBy)
	t.Run("UserCreateCodeToUserUsingUserCreateCodes", testUserCreateCodeToOneRemoveOpUserUsingUser)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("TeamToOwnedByPosts", testTeamToManyAddOpOwnedByPosts)
	t.Run("TeamToTeamMembers", testTeamToManyAddOpTeamMembers)
	t.Run("UserToCreatedByPosts", testUserToManyAddOpCreatedByPosts)
	t.Run("UserToDeletedByPosts", testUserToManyAddOpDeletedByPosts)
	t.Run("UserToUpdatedByPosts", testUserToManyAddOpUpdatedByPosts)
	t.Run("UserToTeamMembers", testUserToManyAddOpTeamMembers)
	t.Run("UserToUserCreateCodes", testUserToManyAddOpUserCreateCodes)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("UserToDeletedByPosts", testUserToManySetOpDeletedByPosts)
	t.Run("UserToUserCreateCodes", testUserToManySetOpUserCreateCodes)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("UserToDeletedByPosts", testUserToManyRemoveOpDeletedByPosts)
	t.Run("UserToUserCreateCodes", testUserToManyRemoveOpUserCreateCodes)
}

func TestReload(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesReload)
	t.Run("Posts", testPostsReload)
	t.Run("TeamMembers", testTeamMembersReload)
	t.Run("Teams", testTeamsReload)
	t.Run("UserCreateCodes", testUserCreateCodesReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesReloadAll)
	t.Run("Posts", testPostsReloadAll)
	t.Run("TeamMembers", testTeamMembersReloadAll)
	t.Run("Teams", testTeamsReloadAll)
	t.Run("UserCreateCodes", testUserCreateCodesReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesSelect)
	t.Run("Posts", testPostsSelect)
	t.Run("TeamMembers", testTeamMembersSelect)
	t.Run("Teams", testTeamsSelect)
	t.Run("UserCreateCodes", testUserCreateCodesSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesUpdate)
	t.Run("Posts", testPostsUpdate)
	t.Run("TeamMembers", testTeamMembersUpdate)
	t.Run("Teams", testTeamsUpdate)
	t.Run("UserCreateCodes", testUserCreateCodesUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesSliceUpdateAll)
	t.Run("Posts", testPostsSliceUpdateAll)
	t.Run("TeamMembers", testTeamMembersSliceUpdateAll)
	t.Run("Teams", testTeamsSliceUpdateAll)
	t.Run("UserCreateCodes", testUserCreateCodesSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
