// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AnalyticsPageviewReferers   string
	AnalyticsPageviewUseragents string
	AnalyticsPageviews          string
	Media                       string
	PostHistory                 string
	Posts                       string
	Subscribers                 string
	TeamMembers                 string
	Teams                       string
	UserCreateCodes             string
	Users                       string
}{
	AnalyticsPageviewReferers:   "analytics_pageview_referers",
	AnalyticsPageviewUseragents: "analytics_pageview_useragents",
	AnalyticsPageviews:          "analytics_pageviews",
	Media:                       "media",
	PostHistory:                 "post_history",
	Posts:                       "posts",
	Subscribers:                 "subscribers",
	TeamMembers:                 "team_members",
	Teams:                       "teams",
	UserCreateCodes:             "user_create_codes",
	Users:                       "users",
}
