// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	PostHistory string
	Posts       string
	TeamMembers string
	Teams       string
	Users       string
}{
	PostHistory: "post_history",
	Posts:       "posts",
	TeamMembers: "team_members",
	Teams:       "teams",
	Users:       "users",
}
