// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("PostHistories", testPostHistoriesUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("TeamMembers", testTeamMembersUpsert)

	t.Run("Teams", testTeamsUpsert)

	t.Run("UserCreateCodes", testUserCreateCodesUpsert)

	t.Run("Users", testUsersUpsert)
}
